lines = [
    "import streamlit as st\n",
    "import httpx\n",
    "from datetime import datetime\n",
    "\n",
    "_DEMO = [\n",
    "    {'content': 'Harika bir hedef! Python icin once temel sozdizimini kavramanı oneririm.', 'suggested_resources': ['Python.org resmi tutorial', 'freeCodeCamp Python kursu'], 'next_step_hint': 'Ilk adim: degisken tanimlama.'},\n",
    "    {'content': 'Ilerleme harika! Kucuk projeler yapman cok faydali olacak.', 'suggested_resources': ['LeetCode Easy', 'Kaggle notebook'], 'next_step_hint': 'Bugun 30 dk pratik yap.'},\n",
    "    {'content': 'Motivasyonunu korumak icin hedefleri kucuk parcalara bol!', 'suggested_resources': ['Pomodoro teknigi'], 'next_step_hint': 'Yarin 1 somut hedef belirle.'},\n",
    "]\n",
    "\n",
    "def show(api_url: str, user_id: str) -> None:\n",
    "    st.title('AI Koc ile Sohbet')\n",
    "    st.caption('Groq LLM destekli kisisel ogrenme kocunuz')\n",
    "    demo_mode = not bool(user_id)\n",
    "    if demo_mode:\n",
    "        st.info('Demo mod: Kullanici ID girmeden de sohbet edebilirsiniz.')\n",
    "\n",
    "    # Sadece ilk acilista karsilama mesajini ekle\n",
    "    if 'chat_initialized' not in st.session_state:\n",
    "        st.session_state.chat_initialized = True\n",
    "        st.session_state.chat_messages = [{\n",
    "            'role': 'assistant',\n",
    "            'content': 'Merhaba! Ben AI ogrenme kocunuzum. Ogrenme hedefleriniz, zorlandiginiz konular veya motivasyon hakkinda benimle konusabilirsiniz. Size nasil yardimci olabilirim?',\n",
    "            'time': datetime.now().strftime('%H:%M'),\n",
    "        }]\n",
    "\n",
    "    col1, col2 = st.columns([5, 1])\n",
    "    with col2:\n",
    "        if st.button('Temizle'):\n",
    "            st.session_state.chat_messages = []\n",
    "            del st.session_state['chat_initialized']\n",
    "            st.rerun()\n",
    "\n",
    "    with st.expander('Hizli Sorular'):\n",
    "        quick_qs = [\n",
    "            'Python ogrenmek istiyorum, nereden baslamaliyim?',\n",
    "            'Bugun motive olamiyorum, ne yapmaliyim?',\n",
    "            'Makine ogrenmesi icin kaynak onerir misin?',\n",
    "            'Haftalik calisma programi nasil yapmaliyim?',\n",
    "        ]\n",
    "        cols = st.columns(2)\n",
    "        for i, q in enumerate(quick_qs):\n",
    "            if cols[i % 2].button(q, key=f'qq_{i}', use_container_width=True):\n",
    "                st.session_state._quick_input = q\n",
    "                st.rerun()\n",
    "\n",
    "    st.divider()\n",
    "\n",
    "    for msg in st.session_state.get('chat_messages', []):\n",
    "        avatar = '👤' if msg['role'] == 'user' else '🎓'\n",
    "        with st.chat_message(msg['role'], avatar=avatar):\n",
    "            st.write(msg['content'])\n",
    "            for res in msg.get('suggested_resources', []):\n",
    "                st.markdown(f'  - {res}')\n",
    "            hint = msg.get('next_step_hint', '')\n",
    "            if hint:\n",
    "                st.info(f'Sonraki Adim: {hint}')\n",
    "            if msg.get('time'):\n",
    "                st.caption(msg['time'])\n",
    "\n",
    "    default_input = st.session_state.pop('_quick_input', '')\n",
    "    user_input = st.chat_input('Kocunuza bir sey sorun...')\n",
    "\n",
    "    if user_input or default_input:\n",
    "        message = user_input or default_input\n",
    "        now = datetime.now().strftime('%H:%M')\n",
    "        st.session_state.chat_messages.append({'role': 'user', 'content': message, 'time': now})\n",
    "        with st.spinner('Kocunuz dusunuyor...'):\n",
    "            if demo_mode:\n",
    "                idx = len(st.session_state.chat_messages) % len(_DEMO)\n",
    "                resp = _DEMO[idx]\n",
    "                ai_msg = {'role': 'assistant', 'content': resp['content'], 'suggested_resources': resp['suggested_resources'], 'next_step_hint': resp['next_step_hint'], 'time': datetime.now().strftime('%H:%M')}\n",
    "            else:\n",
    "                try:\n",
    "                    r = httpx.post(f'{api_url}/coaching/chat', json={'user_id': user_id, 'message': message}, timeout=30)\n",
    "                    r.raise_for_status()\n",
    "                    result = r.json()\n",
    "                    ai_msg = {'role': 'assistant', 'content': result.get('content', ''), 'suggested_resources': result.get('suggested_resources', []), 'next_step_hint': result.get('next_step_hint', ''), 'time': datetime.now().strftime('%H:%M')}\n",
    "                except Exception as e:\n",
    "                    ai_msg = {'role': 'assistant', 'content': f'API baglantisi kurulamadi: {e}', 'time': datetime.now().strftime('%H:%M')}\n",
    "        st.session_state.chat_messages.append(ai_msg)\n",
    "        st.rerun()\n",
]

with open('ai-learning-coach/frontend/_pages/coaching_chat.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)
print('OK')
